### PR TITLE
[SwitchMtpDatabase.h] Removing local_server->sendObjectAdded calls wh…

### PR DESCRIPTION
**Pull request by nadrino**
…ile browsing through with a MTP client. This solved the bug that the server got stuck while browsing through a directory.

[main.cpp] Changing stop key to B.

### CODE REVIEW

**Comment by m4xw** [comment]
What platforms did u test?

**Comment by nadrino** [comment]
On the Switch side, I use the Atmosphere CFW (latest). If you want to test yourself, I put the nro file attached.
On the computer side, I'm on macOS Catalina, latest version, and I use OpenMTP to browse.

[mtp-server-nx.nro.zip](https://github.com/retronx-team/mtp-server-nx/files/4187487/mtp-server-nx.nro.zip)

**Comment by m4xw** [comment]
(Quick reminder that people shouldn't run untrusted bins)
Give me a reminder in 24h and I will check it out, wont have time today.

**Comment by m4xw** [comment]
cc @ckurtz22

**Comment by ckurtz22** [comment]
I can check it out on Ubuntu/Windows 10 tonight if I remember. It seems to me like this might just be a fix for certain MTP clients that was not occurring on Ubuntu/Windows.

(side note regarding the Windows 10 issue, I still have not been able to reproduce on like 4 or 5 different Windows 10 machines. I'll try to double check if I ever tried the release binary tonight as well)

**Comment by m4xw** [comment]
Wtf

**Comment by nadrino** [comment]
Sorry I only have my mac available now. I can't test it on windows/ubuntu for the moment.

**Comment by m4xw** [comment]
Still crashes on Windows for me.

**Comment by m4xw** [comment]
Fixed the win crash, will close this  when i push.

**Pull request closed without merging**
